### ISSUE TITLE
microservices with seneca and node.js crashing containers

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/guides#99]
Run through the sample here: 

https://github.com/weaveworks/guides/pull/98

Launch, the webapp: http://localhost:8080 , then try interacting with the webapp by entering username: u1 and password: U1.  

webapp container exits and crashes.   A `docker logs <container_name>`  produces the following: 

Seneca Fatal Error

```
2015-10-07T18:09:17.986Z    4p8g5oru6u95/1444241337157/1/-  ERROR   plugin  transport       ACT 68oezwmnvnly/isa8r90ny3z1   role:transport,hook:client,type:web client  no-message-id {type=web,port=10101,host=user-ms.weave.local,path=/act,protocol=http,timeout=32778,pin={role=user,cmd=*},msgprefix=seneca_,callmax=111111,msgidlen=12,role=transport,hook=client}    {kind=res,res=,error={code=ENOTFOUND,errno=ENOTFOUND,syscall=getaddrinfo},time={client_recv=1444241357986}}
```

```
Message: seneca: Action cmd:login,role:user failed: [TIMEOUT].

Code: act_execute

Details: { id: 'exhsqly6uzbf/2sc1l1e785nt',
  gate: false,
  ungate: true,
  desc: 'cmd:login,role:user',
  cb: [Function],
  plugin: { name: undefined, tag: undefined },
  fn: [Function],
  time: { start: 1444241357983, end: 1444241391323 },
  'orig$': { [Error: [TIMEOUT]] timeout: true },
  'message$': '[TIMEOUT]',
  message: '[TIMEOUT]',
  pattern: 'cmd:login,role:user',
  instance: 'Seneca/0.6.1/4p8g5oru6u95/1444241337157/1/-' }

Stack: 
    at null._onTimeout (/opt/app/node_modules/seneca/node_modules/gate-executor/gate-executor.js:95:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

Instance: Seneca/0.6.1/4p8g5oru6u95/1444241337157/1/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/opt/app/node_modules/seneca/seneca.js:1423:29)

When: 2015-10-07T18:09:51.327Z

```

**Comment by abuehrle** [comment]
Seems to occur if the wrong username and password are entered, which makes the sample a little on the brittle side.
